version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ajinkya_2401199
      MYSQL_USER: 2401199_AJINKYA
      MYSQL_PASSWORD: PASSWORD123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  attendance:
    build: .
    container_name: attendance_app
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: 2401199_AJINKYA
      DB_PASSWORD: PASSWORD123
      DB_NAME: ajinkya_2401199
      DEBUG: 0
    volumes:
      - static_volume:/app/static
    restart: unless-stopped

volumes:
  mysql_data:
  static_volume: